version: "3.8"
services:
#  rabbitmq:
#    image: rabbitmq:3.13.0-beta.2-management
#    ports:
#      - 5672:5672
#      - 15672:15672
  rabbitmqshovel:
    image: rabbitmqshovelimage
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5672:5672
      - 15672:15672
#  messageredeliverypoc:
#    image: messageredeliverypoc
#    build:
#      context: .
#      dockerfile: Dockerfile
