using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace API.AutoGenerated.Migrations
{
    /// <inheritdoc />
    public partial class UpdateUserAndCompanyTable : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "Tin",
                table: "Users");

            migrationBuilder.DropColumn(
                name: "ProviderId",
                table: "Companies");

            migrationBuilder.CreateIndex(
                name: "IX_Companies_Tin",
                table: "Companies",
                column: "Tin");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_Companies_Tin",
                table: "Companies");

            migrationBuilder.AddColumn<string>(
                name: "Tin",
                table: "Users",
                type: "text",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "ProviderId",
                table: "Companies",
                type: "text",
                nullable: false,
                defaultValue: "");
        }
    }
}
