using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace API.AutoGenerated.Migrations
{
    /// <inheritdoc />
    public partial class AddEiaProviderKeyTypeEnum : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                ALTER TYPE provider_key_type ADD VALUE 'eia' BEFORE 'mit_id_uuid';
            """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                DELETE FROM "UserProviders" WHERE "ProviderKeyType" = 'eia';
                ALTER TABLE "UserProviders" ALTER COLUMN "ProviderKeyType" TYPE varchar(255);
                DROP TYPE provider_key_type;
                CREATE TYPE provider_key_type AS ENUM ('pid', 'rid', 'mit_id_uuid');
                ALTER TABLE "UserProviders" ALTER COLUMN "ProviderKeyType" TYPE provider_key_type USING "ProviderKeyType"::provider_key_type;
            """);
        }
    }
}
