@grantType = client_credentials
@clientId = f75...
@clientSecret = gJP...
@scope = https://datahubeouenerginet.onmicrosoft.com/energy-origin/.default
###

# @name tokenResponse
POST https://datahubeouenerginet.b2clogin.com/datahubeouenerginet.onmicrosoft.com/B2C_1A_ClientCredentials/oauth2/v2.0/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

grant_type={{grantType}}
&client_id={{clientId}}
&client_secret={{clientSecret}}
&scope={{scope}}

###

@accessToken = {{tokenResponse.response.body.access_token}}

GET https://demo.energytrackandtrace.dk/api/authorization/client/consents
Authorization: bearer {{accessToken}}
Content-Type: application/json
X-API-Version: 20230101
