--
-- PostgreSQL database dump
--

-- Dumped from database version 15.7 (Debian 15.7-1.pgdg110+1)
-- Dumped by pg_dump version 15.8

-- Started on 2025-01-14 15:08:45 UTC

---- SET statement_timeout = 0;
---- SET lock_timeout = 0;
---- SET idle_in_transaction_session_timeout = 0;
---- SET client_encoding = 'UTF8';
---- SET standard_conforming_strings = on;
---- SELECT pg_catalog.set_config('search_path', '', false);
---- SET check_function_bodies = false;
---- SET xmloption = content;
---- SET client_min_messages = warning;
---- SET row_security = off;

--
-- TOC entry 3414 (class 1262 OID 16385)
-- Name: authorization-database; Type: DATABASE; Schema: -; Owner: authorization
--

---- CREATE DATABASE "authorization-database" WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'C';


---- ALTER DATABASE "authorization-database" OWNER TO "authorization";

---- \connect -reuse-previous=on "dbname='authorization-database'"

---- SET statement_timeout = 0;
---- SET lock_timeout = 0;
---- SET idle_in_transaction_session_timeout = 0;
---- SET client_encoding = 'UTF8';
---- SET standard_conforming_strings = on;
---- SELECT pg_catalog.set_config('search_path', '', false);
---- SET check_function_bodies = false;
---- SET xmloption = content;
---- SET client_min_messages = warning;
---- SET row_security = off;

--
-- TOC entry 5 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

---- CREATE SCHEMA public;


---- ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- TOC entry 3415 (class 0 OID 0)
-- Dependencies: 5
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

---- COMMENT ON SCHEMA public IS 'standard public schema';


---- SET default_tablespace = '';

---- SET default_table_access_method = heap;

--
-- TOC entry 219 (class 1259 OID 16428)
-- Name: Affiliations; Type: TABLE; Schema: public; Owner: authorization
--

CREATE TABLE public."Affiliations" (
                                       "UserId" uuid NOT NULL,
                                       "OrganizationId" uuid NOT NULL
);


---- ALTER TABLE public."Affiliations" OWNER TO "authorization";

--
-- TOC entry 216 (class 1259 OID 16392)
-- Name: Clients; Type: TABLE; Schema: public; Owner: authorization
--

CREATE TABLE public."Clients" (
                                  "Id" uuid NOT NULL,
                                  "IdpClientId" uuid NOT NULL,
                                  "Name" text NOT NULL,
                                  "ClientType" integer NOT NULL,
                                  "RedirectUrl" text NOT NULL,
                                  "OrganizationId" uuid
);


---- ALTER TABLE public."Clients" OWNER TO "authorization";

--
-- TOC entry 221 (class 1259 OID 16455)
-- Name: InboxState; Type: TABLE; Schema: public; Owner: authorization
--

CREATE TABLE public."InboxState" (
                                     "Id" bigint NOT NULL,
                                     "MessageId" uuid NOT NULL,
                                     "ConsumerId" uuid NOT NULL,
                                     "LockId" uuid NOT NULL,
                                     "RowVersion" bytea,
                                     "Received" timestamp with time zone NOT NULL,
                                     "ReceiveCount" integer NOT NULL,
                                     "ExpirationTime" timestamp with time zone,
                                     "Consumed" timestamp with time zone,
                                     "Delivered" timestamp with time zone,
                                     "LastSequenceNumber" bigint
);


---- ALTER TABLE public."InboxState" OWNER TO "authorization";

--
-- TOC entry 220 (class 1259 OID 16454)
-- Name: InboxState_Id_seq; Type: SEQUENCE; Schema: public; Owner: authorization
--

ALTER TABLE public."InboxState" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."InboxState_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 24704)
-- Name: OrganizationConsents; Type: TABLE; Schema: public; Owner: authorization
--

CREATE TABLE public."OrganizationConsents" (
                                               "Id" uuid NOT NULL,
                                               "ConsentGiverOrganizationId" uuid NOT NULL,
                                               "ConsentReceiverOrganizationId" uuid NOT NULL,
                                               "ConsentDate" timestamp with time zone NOT NULL
);


---- ALTER TABLE public."OrganizationConsents" OWNER TO "authorization";

--
-- TOC entry 217 (class 1259 OID 16399)
-- Name: Organizations; Type: TABLE; Schema: public; Owner: authorization
--

CREATE TABLE public."Organizations" (
                                        "Id" uuid NOT NULL,
                                        "Tin" text,
                                        "Name" text NOT NULL,
                                        "TermsAcceptanceDate" timestamp with time zone,
                                        "TermsAccepted" boolean DEFAULT false NOT NULL,
                                        "TermsVersion" integer,
                                        "ServiceProviderTermsAcceptanceDate" timestamp with time zone,
                                        "ServiceProviderTermsAccepted" boolean DEFAULT false NOT NULL
);


---- ALTER TABLE public."Organizations" OWNER TO "authorization";

--
-- TOC entry 223 (class 1259 OID 16465)
-- Name: OutboxMessage; Type: TABLE; Schema: public; Owner: authorization
--

CREATE TABLE public."OutboxMessage" (
                                        "SequenceNumber" bigint NOT NULL,
                                        "EnqueueTime" timestamp with time zone,
                                        "SentTime" timestamp with time zone NOT NULL,
                                        "Headers" text,
                                        "Properties" text,
                                        "InboxMessageId" uuid,
                                        "InboxConsumerId" uuid,
                                        "OutboxId" uuid,
                                        "MessageId" uuid NOT NULL,
                                        "ContentType" character varying(256) NOT NULL,
                                        "MessageType" text NOT NULL,
                                        "Body" text NOT NULL,
                                        "ConversationId" uuid,
                                        "CorrelationId" uuid,
                                        "InitiatorId" uuid,
                                        "RequestId" uuid,
                                        "SourceAddress" character varying(256),
                                        "DestinationAddress" character varying(256),
                                        "ResponseAddress" character varying(256),
                                        "FaultAddress" character varying(256),
                                        "ExpirationTime" timestamp with time zone
);


---- ALTER TABLE public."OutboxMessage" OWNER TO "authorization";

--
-- TOC entry 222 (class 1259 OID 16464)
-- Name: OutboxMessage_SequenceNumber_seq; Type: SEQUENCE; Schema: public; Owner: authorization
--

ALTER TABLE public."OutboxMessage" ALTER COLUMN "SequenceNumber" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."OutboxMessage_SequenceNumber_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 16472)
-- Name: OutboxState; Type: TABLE; Schema: public; Owner: authorization
--

CREATE TABLE public."OutboxState" (
                                      "OutboxId" uuid NOT NULL,
                                      "LockId" uuid NOT NULL,
                                      "RowVersion" bytea,
                                      "Created" timestamp with time zone NOT NULL,
                                      "Delivered" timestamp with time zone,
                                      "LastSequenceNumber" bigint
);


---- ALTER TABLE public."OutboxState" OWNER TO "authorization";

--
-- TOC entry 225 (class 1259 OID 16479)
-- Name: Terms; Type: TABLE; Schema: public; Owner: authorization
--

CREATE TABLE public."Terms" (
                                "Id" uuid NOT NULL,
                                "Version" integer NOT NULL
);


---- ALTER TABLE public."Terms" OWNER TO "authorization";

--
-- TOC entry 218 (class 1259 OID 16406)
-- Name: Users; Type: TABLE; Schema: public; Owner: authorization
--

CREATE TABLE public."Users" (
                                "Id" uuid NOT NULL,
                                "IdpUserId" uuid NOT NULL,
                                "Name" text NOT NULL
);


---- ALTER TABLE public."Users" OWNER TO "authorization";

--
-- TOC entry 215 (class 1259 OID 16387)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: authorization
--

CREATE TABLE public."__EFMigrationsHistory" (
                                                "MigrationId" character varying(150) NOT NULL,
                                                "ProductVersion" character varying(32) NOT NULL
);


---- ALTER TABLE public."__EFMigrationsHistory" OWNER TO "authorization";

--
-- TOC entry 3242 (class 2606 OID 16463)
-- Name: InboxState AK_InboxState_MessageId_ConsumerId; Type: CONSTRAINT; Schema: public; Owner: authorization
--

ALTER TABLE ONLY public."InboxState"
    ADD CONSTRAINT "AK_InboxState_MessageId_ConsumerId" UNIQUE ("MessageId", "ConsumerId");


--
-- TOC entry 3240 (class 2606 OID 16432)
-- Name: Affiliations PK_Affiliations; Type: CONSTRAINT; Schema: public; Owner: authorization
--

ALTER TABLE ONLY public."Affiliations"
    ADD CONSTRAINT "PK_Affiliations" PRIMARY KEY ("UserId", "OrganizationId");


--
-- TOC entry 3231 (class 2606 OID 16398)
-- Name: Clients PK_Clients; Type: CONSTRAINT; Schema: public; Owner: authorization
--

ALTER TABLE ONLY public."Clients"
    ADD CONSTRAINT "PK_Clients" PRIMARY KEY ("Id");


--
-- TOC entry 3245 (class 2606 OID 16461)
-- Name: InboxState PK_InboxState; Type: CONSTRAINT; Schema: public; Owner: authorization
--

ALTER TABLE ONLY public."InboxState"
    ADD CONSTRAINT "PK_InboxState" PRIMARY KEY ("Id");


--
-- TOC entry 3261 (class 2606 OID 24708)
-- Name: OrganizationConsents PK_OrganizationConsents; Type: CONSTRAINT; Schema: public; Owner: authorization
--

ALTER TABLE ONLY public."OrganizationConsents"
    ADD CONSTRAINT "PK_OrganizationConsents" PRIMARY KEY ("Id");


--
-- TOC entry 3234 (class 2606 OID 16405)
-- Name: Organizations PK_Organizations; Type: CONSTRAINT; Schema: public; Owner: authorization
--

ALTER TABLE ONLY public."Organizations"
    ADD CONSTRAINT "PK_Organizations" PRIMARY KEY ("Id");


--
-- TOC entry 3251 (class 2606 OID 16471)
-- Name: OutboxMessage PK_OutboxMessage; Type: CONSTRAINT; Schema: public; Owner: authorization
--

ALTER TABLE ONLY public."OutboxMessage"
    ADD CONSTRAINT "PK_OutboxMessage" PRIMARY KEY ("SequenceNumber");


--
-- TOC entry 3254 (class 2606 OID 16478)
-- Name: OutboxState PK_OutboxState; Type: CONSTRAINT; Schema: public; Owner: authorization
--

ALTER TABLE ONLY public."OutboxState"
    ADD CONSTRAINT "PK_OutboxState" PRIMARY KEY ("OutboxId");


--
-- TOC entry 3257 (class 2606 OID 16483)
-- Name: Terms PK_Terms; Type: CONSTRAINT; Schema: public; Owner: authorization
--

ALTER TABLE ONLY public."Terms"
    ADD CONSTRAINT "PK_Terms" PRIMARY KEY ("Id");


--
-- TOC entry 3237 (class 2606 OID 16412)
-- Name: Users PK_Users; Type: CONSTRAINT; Schema: public; Owner: authorization
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "PK_Users" PRIMARY KEY ("Id");


--
-- TOC entry 3227 (class 2606 OID 16391)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: authorization
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 3238 (class 1259 OID 16443)
-- Name: IX_Affiliations_OrganizationId; Type: INDEX; Schema: public; Owner: authorization
--

CREATE INDEX "IX_Affiliations_OrganizationId" ON public."Affiliations" USING btree ("OrganizationId");


--
-- TOC entry 3228 (class 1259 OID 16444)
-- Name: IX_Clients_IdpClientId; Type: INDEX; Schema: public; Owner: authorization
--

CREATE UNIQUE INDEX "IX_Clients_IdpClientId" ON public."Clients" USING btree ("IdpClientId");


--
-- TOC entry 3229 (class 1259 OID 24719)
-- Name: IX_Clients_OrganizationId; Type: INDEX; Schema: public; Owner: authorization
--

CREATE INDEX "IX_Clients_OrganizationId" ON public."Clients" USING btree ("OrganizationId");


--
-- TOC entry 3243 (class 1259 OID 16484)
-- Name: IX_InboxState_Delivered; Type: INDEX; Schema: public; Owner: authorization
--

CREATE INDEX "IX_InboxState_Delivered" ON public."InboxState" USING btree ("Delivered");


--
-- TOC entry 3258 (class 1259 OID 24720)
-- Name: IX_OrganizationConsents_ConsentGiverOrganizationId; Type: INDEX; Schema: public; Owner: authorization
--

CREATE INDEX "IX_OrganizationConsents_ConsentGiverOrganizationId" ON public."OrganizationConsents" USING btree ("ConsentGiverOrganizationId");


--
-- TOC entry 3259 (class 1259 OID 24727)
-- Name: IX_OrganizationConsents_ConsentReceiverOrganizationId_ConsentG~; Type: INDEX; Schema: public; Owner: authorization
--

CREATE UNIQUE INDEX "IX_OrganizationConsents_ConsentReceiverOrganizationId_ConsentG~" ON public."OrganizationConsents" USING btree ("ConsentReceiverOrganizationId", "ConsentGiverOrganizationId");


--
-- TOC entry 3232 (class 1259 OID 16448)
-- Name: IX_Organizations_Tin; Type: INDEX; Schema: public; Owner: authorization
--

CREATE UNIQUE INDEX "IX_Organizations_Tin" ON public."Organizations" USING btree ("Tin");


--
-- TOC entry 3246 (class 1259 OID 16485)
-- Name: IX_OutboxMessage_EnqueueTime; Type: INDEX; Schema: public; Owner: authorization
--

CREATE INDEX "IX_OutboxMessage_EnqueueTime" ON public."OutboxMessage" USING btree ("EnqueueTime");


--
-- TOC entry 3247 (class 1259 OID 16486)
-- Name: IX_OutboxMessage_ExpirationTime; Type: INDEX; Schema: public; Owner: authorization
--

CREATE INDEX "IX_OutboxMessage_ExpirationTime" ON public."OutboxMessage" USING btree ("ExpirationTime");


--
-- TOC entry 3248 (class 1259 OID 16487)
-- Name: IX_OutboxMessage_InboxMessageId_InboxConsumerId_SequenceNumber; Type: INDEX; Schema: public; Owner: authorization
--

CREATE UNIQUE INDEX "IX_OutboxMessage_InboxMessageId_InboxConsumerId_SequenceNumber" ON public."OutboxMessage" USING btree ("InboxMessageId", "InboxConsumerId", "SequenceNumber");


--
-- TOC entry 3249 (class 1259 OID 16488)
-- Name: IX_OutboxMessage_OutboxId_SequenceNumber; Type: INDEX; Schema: public; Owner: authorization
--

CREATE UNIQUE INDEX "IX_OutboxMessage_OutboxId_SequenceNumber" ON public."OutboxMessage" USING btree ("OutboxId", "SequenceNumber");


--
-- TOC entry 3252 (class 1259 OID 16489)
-- Name: IX_OutboxState_Created; Type: INDEX; Schema: public; Owner: authorization
--

CREATE INDEX "IX_OutboxState_Created" ON public."OutboxState" USING btree ("Created");


--
-- TOC entry 3255 (class 1259 OID 16490)
-- Name: IX_Terms_Version; Type: INDEX; Schema: public; Owner: authorization
--

CREATE UNIQUE INDEX "IX_Terms_Version" ON public."Terms" USING btree ("Version");


--
-- TOC entry 3235 (class 1259 OID 16447)
-- Name: IX_Users_IdpUserId; Type: INDEX; Schema: public; Owner: authorization
--

CREATE UNIQUE INDEX "IX_Users_IdpUserId" ON public."Users" USING btree ("IdpUserId");


--
-- TOC entry 3263 (class 2606 OID 16433)
-- Name: Affiliations FK_Affiliations_Organizations_OrganizationId; Type: FK CONSTRAINT; Schema: public; Owner: authorization
--

ALTER TABLE ONLY public."Affiliations"
    ADD CONSTRAINT "FK_Affiliations_Organizations_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES public."Organizations"("Id") ON DELETE CASCADE;


--
-- TOC entry 3264 (class 2606 OID 16438)
-- Name: Affiliations FK_Affiliations_Users_UserId; Type: FK CONSTRAINT; Schema: public; Owner: authorization
--

ALTER TABLE ONLY public."Affiliations"
    ADD CONSTRAINT "FK_Affiliations_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id") ON DELETE CASCADE;


--
-- TOC entry 3262 (class 2606 OID 24722)
-- Name: Clients FK_Clients_Organizations_OrganizationId; Type: FK CONSTRAINT; Schema: public; Owner: authorization
--

ALTER TABLE ONLY public."Clients"
    ADD CONSTRAINT "FK_Clients_Organizations_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES public."Organizations"("Id");


--
-- TOC entry 3265 (class 2606 OID 24709)
-- Name: OrganizationConsents FK_OrganizationConsents_Organizations_ConsentGiverOrganization~; Type: FK CONSTRAINT; Schema: public; Owner: authorization
--

ALTER TABLE ONLY public."OrganizationConsents"
    ADD CONSTRAINT "FK_OrganizationConsents_Organizations_ConsentGiverOrganization~" FOREIGN KEY ("ConsentGiverOrganizationId") REFERENCES public."Organizations"("Id") ON DELETE CASCADE;


--
-- TOC entry 3266 (class 2606 OID 24714)
-- Name: OrganizationConsents FK_OrganizationConsents_Organizations_ConsentReceiverOrganizat~; Type: FK CONSTRAINT; Schema: public; Owner: authorization
--

ALTER TABLE ONLY public."OrganizationConsents"
    ADD CONSTRAINT "FK_OrganizationConsents_Organizations_ConsentReceiverOrganizat~" FOREIGN KEY ("ConsentReceiverOrganizationId") REFERENCES public."Organizations"("Id") ON DELETE CASCADE;


-- Completed on 2025-01-14 15:08:45 UTC

--
-- PostgreSQL database dump complete
--

