DO
$$
    BEGIN
        IF NOT EXISTS
            (SELECT 1
             FROM information_schema.tables
             WHERE table_schema = 'public'
               AND table_name = 'InboxState')
        THEN

            CREATE TABLE public."InboxState"
            (
                "Id"                 bigint                   NOT NULL,
                "MessageId"          uuid                     NOT NULL,
                "ConsumerId"         uuid                     NOT NULL,
                "LockId"             uuid                     NOT NULL,
                "RowVersion"         bytea,
                "Received"           timestamp with time zone NOT NULL,
                "ReceiveCount"       integer                  NOT NULL,
                "ExpirationTime"     timestamp with time zone,
                "Consumed"           timestamp with time zone,
                "Delivered"          timestamp with time zone,
                "LastSequenceNumber" bigint
            );

            ALTER TABLE public."InboxState"
            ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
                                SEQUENCE NAME public."InboxState_Id_seq"
                                START WITH 1
                                INCREMENT BY 1
                                NO MINVALUE
                                NO MAXVALUE
                                CACHE 1
                                );

            ALTER TABLE ONLY public."InboxState"
                ADD CONSTRAINT "AK_InboxState_MessageId_ConsumerId" UNIQUE ("MessageId", "ConsumerId");

            ALTER TABLE ONLY public."InboxState"
                ADD CONSTRAINT "PK_InboxState" PRIMARY KEY ("Id");

            CREATE INDEX "IX_InboxState_Delivered" ON public."InboxState" USING btree ("Delivered");

        END IF;
    END;
$$;

DO
$$
    BEGIN
        IF NOT EXISTS
            (SELECT 1
             FROM information_schema.tables
             WHERE table_schema = 'public'
               AND table_name = 'OutboxMessage')
        THEN

            CREATE TABLE public."OutboxMessage"
            (
                "SequenceNumber"     bigint                   NOT NULL,
                "EnqueueTime"        timestamp with time zone,
                "SentTime"           timestamp with time zone NOT NULL,
                "Headers"            text,
                "Properties"         text,
                "InboxMessageId"     uuid,
                "InboxConsumerId"    uuid,
                "OutboxId"           uuid,
                "MessageId"          uuid                     NOT NULL,
                "ContentType"        character varying(256)   NOT NULL,
                "MessageType"        text                     NOT NULL,
                "Body"               text                     NOT NULL,
                "ConversationId"     uuid,
                "CorrelationId"      uuid,
                "InitiatorId"        uuid,
                "RequestId"          uuid,
                "SourceAddress"      character varying(256),
                "DestinationAddress" character varying(256),
                "ResponseAddress"    character varying(256),
                "FaultAddress"       character varying(256),
                "ExpirationTime"     timestamp with time zone
            );

            ALTER TABLE public."OutboxMessage"
            ALTER COLUMN "SequenceNumber" ADD GENERATED BY DEFAULT AS IDENTITY (
                                SEQUENCE NAME public."OutboxMessage_SequenceNumber_seq"
                                START WITH 1
                                INCREMENT BY 1
                                NO MINVALUE
                                NO MAXVALUE
                                CACHE 1
                                );

            ALTER TABLE ONLY public."OutboxMessage"
                ADD CONSTRAINT "PK_OutboxMessage" PRIMARY KEY ("SequenceNumber");

            CREATE INDEX "IX_OutboxMessage_EnqueueTime" ON public."OutboxMessage" USING btree ("EnqueueTime");

            CREATE INDEX "IX_OutboxMessage_ExpirationTime" ON public."OutboxMessage" USING btree ("ExpirationTime");

            CREATE UNIQUE INDEX "IX_OutboxMessage_InboxMessageId_InboxConsumerId_SequenceNumber" ON public."OutboxMessage" USING btree ("InboxMessageId", "InboxConsumerId", "SequenceNumber");

            CREATE UNIQUE INDEX "IX_OutboxMessage_OutboxId_SequenceNumber" ON public."OutboxMessage" USING btree ("OutboxId", "SequenceNumber");

        END IF;
    END;
$$;


DO
$$
    BEGIN
        IF NOT EXISTS
            (SELECT 1
             FROM information_schema.tables
             WHERE table_schema = 'public'
               AND table_name = 'OutboxState')
        THEN

            CREATE TABLE public."OutboxState"
            (
                "OutboxId"           uuid                     NOT NULL,
                "LockId"             uuid                     NOT NULL,
                "RowVersion"         bytea,
                "Created"            timestamp with time zone NOT NULL,
                "Delivered"          timestamp with time zone,
                "LastSequenceNumber" bigint
            );

            ALTER TABLE ONLY public."OutboxState"
                ADD CONSTRAINT "PK_OutboxState" PRIMARY KEY ("OutboxId");

            CREATE INDEX "IX_OutboxState_Created" ON public."OutboxState" USING btree ("Created");

        END IF;
    END;
$$;
