name: Dotnet Validate

description: Lints and tests a domain.

inputs:
  subsystem:
    description: The name of the subsystem (e.g., transfer, authorization)
    required: true

  sdk-version:
    description: Is a complete sdk version in format x.y.zzz (optional override)
    required: false
    default: ""

  pin-version:
    description: Pin dotnet version
    default: "false"
    required: false

runs:
  using: composite

  steps:
    - name: Load SDK version from global.json
      shell: bash
      id: load-sdk
      run: |
        DIRECTORY="domains/${{ inputs.subsystem }}"
        test -f "$DIRECTORY/global.json" || echo "No global.json found in $DIRECTORY"
        if [ -f "$DIRECTORY/global.json" ]; then
          echo "SDK=$(jq -rc '.sdk.version' "$DIRECTORY/global.json")" >> $GITHUB_ENV
          echo "DIRECTORY=$DIRECTORY" >> $GITHUB_ENV
        fi

    - name: Overwrite SDK version if provided
      shell: bash
      run: |
        if [ ! -z "${{ inputs.sdk-version }}" ]; then
          echo "SDK=${{ inputs.sdk-version }}" >> $GITHUB_ENV
        fi

    - name: Fail if SDK version is not present
      shell: bash
      run: |
        if [ -z "${{ env.SDK }}" ]; then
          echo "No SDK version found in global.json and none provided as input"
          exit 1
        fi

    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.SDK }}

    - name: Create dynamic solution file
      shell: bash
      run: |
        rm -f EnergyTrackAndTrace.sln
        dotnet new sln -n ${{ inputs.subsystem }}
        find domains/${{ inputs.subsystem }} -name '*.csproj' | while read project; do
          dotnet sln ${{ inputs.subsystem }}.sln add "$project"
        done

    - name: Cache NuGet packages
      uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Pin version
      working-directory: ${{ env.DIRECTORY }}
      shell: bash
      if: ${{ inputs.pin-version == 'true' }}
      run: printf '{"sdk":{"rollForward":"disable","version":"%s"}}' "${{ env.SDK }}" > global.json

    - name: Print dotnet version
      shell: bash
      run: dotnet --version

    - name: Print dotnet information
      shell: bash
      run: dotnet --info

    - name: Restore
      shell: bash
      env:
        version: ""
      run: |
        dotnet tool restore || true
        dotnet restore ${{ inputs.subsystem }}.sln

    - name: Test
      shell: bash
      env:
        DOTNET_NOLOGO: "true"
        DOTNET_CLI_TELEMETRY_OPTOUT: "true"
        DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION: "true"
        TERM: "xterm"
        version: ""
      run: dotnet test ${{ inputs.subsystem }}.sln --no-restore -warnaserror --logger:"console;verbosity=minimal" -p:ParallelizeAssemblies=true -p:ParallelizeTestCollections=true
