name: Build Subsystems

on:
  workflow_call:
    inputs:
      dry-run:
        description: "An indication of whether to commit/publish results"
        required: true
        type: string
      is-dependabot:
        description: "An indication of a dependabot pull request"
        required: true
        type: string

jobs:
  dotnet-lint-solution:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run dotnet format
        uses: ./.github/actions/dotnet-lint-solution
        with:
          path: "domains"

  test-subsystems:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        subsystem: [transfer, admin-portal, authorization, measurements, certificates, oidc-mock]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: ${{ format('{0}{1}', upper(substring(matrix.subsystem, 0, 1)), substring(matrix.subsystem, 1)) }}
        uses: ./.github/actions/dotnet-validate-solution
        with:
          subsystem: ${{ matrix.subsystem }}
          pin-version: "true"

  build-images:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - subsystem: admin-portal
            solution: domains/admin-portal/AdminPortal.sln
            project: domains/admin-portal/AdminPortal.Web/AdminPortal/AdminPortal.csproj
            configuration: domains/admin-portal/AdminPortal.Web/configuration.yaml

          # Authorization
          - subsystem: authorization
            solution: Authorization.sln
            project: domains/authorization/Authorization.API/API/API.csproj
            configuration: domains/authorization/Authorization.API/configuration.yaml
            name: Authorization.API

          - subsystem: authorization
            solution: Authorization.sln
            project: domains/authorization/Proxy/Proxy.csproj
            configuration: domains/authorization/Proxy/configuration.yaml
            name: Authorization.Proxy

          # Certificates
          - subsystem: certificates
            solution: Certificates.sln
            project: domains/certificates/Query.API/API/API.csproj
            configuration: domains/certificates/Query.API/configuration.yaml
            name: Query.API

          # Measurements
          - subsystem: measurements
            solution: Measurements.sln
            project: domains/measurements/Measurements.API/API/API.csproj
            configuration: domains/measurements/Measurements.API/configuration.yaml
            name: Measurements.API

          # OIDC Mock
          - subsystem: oidc-mock
            solution: Oidc.Mock.sln
            project: domains/oidc-mock/API/API.csproj
            configuration: domains/oidc-mock/API/configuration.yaml
            name: Oidc.Mock.API

          # Transfer
          - subsystem: transfer
            solution: Transfer.sln
            project: domains/transfer/Transfer.API/API/API.csproj
            configuration: domains/transfer/Transfer.API/configuration.yaml
            name: Transfer.API

          - subsystem: transfer
            solution: Transfer.sln
            project: domains/transfer/ClaimAutomation/Worker/Worker.csproj
            configuration: domains/transfer/ClaimAutomation/configuration.yaml
            name: ClaimAutomation.Worker

          - subsystem: transfer
            solution: Transfer.sln
            project: domains/transfer/TransferAgreementAutomation/Worker/Worker.csproj
            configuration: domains/transfer/TransferAgreementAutomation/configuration.yaml
            name: TransferAutomation.Worker
      fail-fast: false

  # redoc
  build-openapi:
    uses: ./.github/workflows/build-openapi.yaml
    secrets: inherit
    with:
      dry-run: ${{ inputs.dry-run }}
      is-dependabot: ${{ inputs.is-dependabot }}

    steps:
      - uses: actions/checkout@v4

      - name: Build ${{ matrix.project }}
        uses: ./.github/actions/dotnet-build
        with:
          solution: ${{ matrix.solution }}
          project: ${{ matrix.project }}
          configuration: ${{ matrix.configuration }}
          dry-run: ${{ inputs.dry-run }}

  update:
    runs-on: ubuntu-latest
    name: Update environment
    needs:
      - dotnet-lint-solution
      - test-subsystems
      - build-openapi
    concurrency: commits-base-environment
    if: ${{ inputs.is-dependabot == 'false' }}
    steps:
      - uses: actions/checkout@v4

      - name: Update environment
        uses: Energinet-DataHub/acorn-actions/actions/update-base-environment@v4
        with:
          configurations: |
            domains/admin-portal/AdminPortal.Web/configuration.yaml
            domains/authorization/Authorization.API/configuration.yaml
            domains/authorization/Proxy/configuration.yaml
            domains/certificates/Query.API/configuration.yaml
            domains/measurements/Measurements.API/configuration.yaml
            domains/oidc-mock/API/configuration.yaml
            domains/transfer/Transfer.API/configuration.yaml
            domains/transfer/ClaimAutomation/configuration.yaml
            domains/transfer/TransferAgreementAutomation/configuration.yaml
            domains/redoc/configuration.yaml
          dry_run: ${{ inputs.dry-run }}
          github-app-id: ${{ vars.ACORN_GHA_APP_ID }}
          github-app-private-key: ${{ secrets.ACORN_GHA_PRIVATE_KEY }}
